package com.metacto.kmm.appsflyer.util

object AppsFlyerConstants {
    const val PID = "pid"
    const val C = "c"
    const val AF_PRT = "af_prt"
    const val AF_MP = "af_mp"
    const val CLICKID = "clickid"
    const val AF_SITEID = "af_siteid"
    const val AF_SUB_SITEID = "af_sub_siteid"
    const val AF_C_ID = "af_c_id"
    const val AF_ADSET = "af_adset"
    const val AF_ADSET_ID = "af_adset_id"
    const val AF_AD = "af_ad"
    const val AF_AD_ID = "af_ad_id"
    const val AF_AD_TYPE = "af_ad_type"
    const val AF_AD_FORMAT = "af_ad_format"
    const val AF_CLICK_LOOKBACK = "af_click_lookback"
    const val AF_VIEWTHROUGH_LOOKBACK = "af_viewthrough_lookback"
    const val AF_CHANNEL = "af_channel"
    const val AF_KEYWORDS = "af_keywords"
    const val AF_COST_MODEL = "af_cost_model"
    const val AF_COST_CURRENCY = "af_cost_currency"
    const val AF_COST_VALUE = "af_cost_value"

    const val AF_SUB1 = "af_sub1"
    const val AF_SUB2 = "af_sub2"
    const val AF_SUB3 = "af_sub3"
    const val AF_SUB4 = "af_sub4"
    const val AF_SUB5 = "af_sub5"

    const val DEEP_LINK_SUB1 = "deep_link_sub1"
    const val DEEP_LINK_SUB2 = "deep_link_sub2"
    const val DEEP_LINK_SUB3 = "deep_link_sub3"
    const val DEEP_LINK_SUB4 = "deep_link_sub4"
    const val DEEP_LINK_SUB5 = "deep_link_sub5"
    const val DEEP_LINK_SUB6 = "deep_link_sub6"
    const val DEEP_LINK_SUB7 = "deep_link_sub7"
    const val DEEP_LINK_SUB8 = "deep_link_sub8"
    const val DEEP_LINK_SUB9 = "deep_link_sub9"
    const val DEEP_LINK_SUB10 = "deep_link_sub10"

    const val AF_R = "af_r"
    const val AF_WEB_DP = "af_web_dp"
    const val BASE_DEEP_LINK = "af_dp"
    const val AF_FORCE_DEEPLINK = "af_force_deeplink"
    const val AF_REF = "af_ref"
    const val IS_INCENTIVIZED = "is_incentivized"
    const val AF_PARAM_FORWARDING = "af_param_forwarding"
    const val AF_BASE_PARAMS_FORWARD = "af_base_params_forward"
    const val AF_PARTNER_ACCOUNT_ID = "af_partner_account_id"
    const val AF_UA = "af_ua"
    const val AF_IP = "af_ip"
    const val AF_OS = "af_os"
    const val AF_OS_VERSION = "af_os_version"
    const val AF_MODEL = "af_model"
    const val AF_MEDIA_TYPE = "af_media_type"
    const val DEEP_LINK_VALUE = "deep_link_value"
    const val AF_OG_TITLE = "af_og_title"
    const val AF_OG_DESCRIPTION = "af_og_description"
    const val AF_OG_IMAGE = "af_og_image"
    const val IS_RETARGETING = "is_retargeting"
    const val AF_REENGAGEMENT_WINDOW = "af_reengagement_window"

    const val AF_VIDEO_TOTAL_LENGTH = "af_video_total_length"
    const val AF_VIDEO_PLAYED_LENGTH = "af_video_played_length"
    const val AF_PLAYABLE_PLAYED_LENGTH = "af_playable_played_length"
    const val AF_AD_TIME_VIEWED = "af_ad_time_viewed"
    const val AF_AD_DISPLAYED_PERCENT = "af_ad_displayed_percent"
    const val AF_AUDIO_TOTAL_LENGTH = "af_audio_total_length"
    const val AF_AUDIO_PLAYED_LENGTH = "af_audio_played_length"

    const val ADVERTISING_ID = "advertising_id"
    const val SHA1_ADVERTISING_ID = "sha1_advertising_id"
    const val MD5_ADVERTISING_ID = "md5_advertising_id"
    const val ANDROID_ID = "android_id"
    const val SHA1_ANDROID_ID = "sha1_android_id"
    const val MD5_ANDROID_ID = "md5_android_id"
    const val IMEI = "imei"
    const val SHA1_IMEI = "sha1_imei"
    const val MD5_IMEI = "md5_imei"
    const val OAID = "oaid"
    const val SHA1_OAID = "sha1_oaid"
    const val MD5_OAID = "md5_oaid"
    const val AF_ANDROID_URL = "af_android_url"
    const val SHA1_EL = "sha1_el"
    const val FIRE_ADVERTISING_ID = "fire_advertising_id"
    const val AF_ANDROID_STORE_CSL = "af_android_store_csl"

    const val IDFA = "idfa"
    const val IDFV = "idfv"
    const val AF_IOS_URL = "af_ios_url"
    const val AF_IOS_STORE_CPP = "af_ios_store_cpp"
    const val SHA1_IDFA = "sha1_idfa"
    const val SHA1_IDFV = "sha1_idfv"
    const val MAC = "mac"
    const val MD5_IDFA = "md5_idfa"
    const val MD5_IDFV = "md5_idfv"
    const val SHA1_MAC = "sha1_mac"

    const val MEDIA_SOURCE = "media_source"
    const val INSTALL_TIME = "install_time"
    const val CLICK_TIME = "click_time"
    const val IS_FIRST_LAUNCH = "is_first_launch"
    const val AF_STATUS = "af_status"
    const val ADGROUP_ID = "adgroup_id"
    const val ADSET = "adset"
    const val ADSET_ID = "adset_id"
    const val AGENCY = "agency"
    const val CAMPAIGN = "campaign"
    const val CAMPAIGN_ID = "campaign_id"
    const val HTTP_REFERRER = "http_referrer"
    const val RETARGETING_CONVERSION_TYPE = "retargeting_conversion_type"
    const val ORIG_COST = "orig_cost"
    const val COST_CENTS_USD = "cost_cents_USD"
    const val AF_CPI = "af_cpi"

    const val MATCH_TYPE = "match_type"
    const val AD_ID = "ad_id"
    const val IS_FB = "is_fb"
    const val IS_PAID = "is_paid"
    const val ADGROUP = "adgroup"
    const val ADGROUP_NAME = "adgroup_name"
    const val IS_INSTAGRAM = "is_instagram"

    const val EXTERNAL_ACCOUNT_ID = "external_account_id"
    const val GCLID = "gclid"
    const val LAT = "lat"
    const val NETWORK = "network"
    const val CLICK_URL = "click_url"
    const val VIDEO_ID = "video_id"
    const val AD_EVENT_ID = "ad_event_id"

    const val CAMPAIGN_TYPE = "campaign_type"

    const val AF_ORGANIC_STATUS = "Organic"

    const val DEEP_LINK_DESTINATION = "deep_link_destination"
    const val REFERRER_NAME = "af_referrer_name"
    const val REFERRER_CUSTOMER_ID = "af_referrer_customer_id"
    const val REFERRER_UID = "af_referrer_uid"
    const val REFERRER_IMAGE_URL = "af_referrer_image_url"
}
